version: '3.8'
services:
  fastapi_db:
    image: "postgres:17.5"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - ./db-data/fastapi_db/:/var/lib/postgresql/data