name: Build and Deploy FastAPI App

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5472
      DATABASE_USERNAME: fastapi_sm_user
      DATABASE_PASSWORD: password123
      DATABASE_NAME: fastapi_sm_db
      SECRET_KEY: yaarasecret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python version 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      # Install dependencies
      - name: Upgrade pip and Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # # Run tests
      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest tests/
    
      # # Build the application
      # - name: Deploy to server
      #   run: |
      #     echo "Deploying to server..."
