name: Build and Deploy FastAPI App

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

on: [push, pull_request]

jobs:
  job1:
    environment: 
      name: testing
    env:
      DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python version 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      # Install dependencies
      - name: Upgrade pip and Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # # Run tests
      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest tests/
    
      # # Build the application
      # - name: Deploy to server
      #   run: |
      #     echo "Deploying to server..."
