name: Build and Deploy FastAPI App

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo "Hello, World!"

      # Set up Python environment
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.9'
      # # Install dependencies
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # # Run tests
      # - name: Run tests
      #   run: |
      #     pytest tests/
      # # Build the application
      # - name: Deploy to server
      #   run: |
      #     echo "Deploying to server..."
